### ISSUE TITLE
Redis exception on post create

### ISSUE THREAD

**Issue by techiedesu** [lewd-site/TinyIB#97]
Application throws redis exception when cache was disabled.

.env

```
...
# Cache configuration

# CACHE possible values:
#   ''      - no caching.
#   'redis' - use redis for cache.
CACHE=

# Redis cache host
CACHE_REDIS_HOST #=unix:/var/run/redis/redis.sock
...
```

Stack trace
```
Connection.php:127
Stack trace:
#0 [internal function]: Imageboard\App->Imageboard\{closure}(2, 'stream_socket_c...', '/mnt/c/Users/te...', 127, Array)
#1 /mnt/c/Users/techiedesu/source/repos/TinyIB/vendor/predis/predis/src/Connection/StreamConnection.php(127): stream_socket_client('unix:///var/run...', 2, 'No such file or...', 5, 4)
#2 /mnt/c/Users/techiedesu/source/repos/TinyIB/vendor/predis/predis/src/Connection/StreamConnection.php(210): Predis\Connection\StreamConnection->createStreamSocket(Object(Predis\Connection\Parameters), 'unix:///var/run...', 4)
#3 /mnt/c/Users/techiedesu/source/repos/TinyIB/vendor/predis/predis/src/Connection/StreamConnection.php(103): Predis\Connection\StreamConnection->unixStreamInitializer(Object(Predis\Connection\Parameters))
#4 /mnt/c/Users/techiedesu/source/ in /mnt/c/Users/techiedesu/source/repos/TinyIB/vendor/predis/predis/src/Connection/StreamConnection.php on line 127
```

**Comment by techiedesu** [comment]
@VVatashi 

Do not forget to add `REDIS_ENABLE=true` on server!
